### ISSUE TITLE
Extension not working in Magento 2.2.7

### ISSUE THREAD

**Issue by EnigmaWebdesign** [magenizr/Magenizr_CustomShipping#1]
Hi all,

I was surprised by this nice extension and installed it but after installing and configuring I found out that this extension isn't working.

It doesn't hide other shipping extensions and in my case it does hide itself in the frontend but also in the backend. Might be doing something wrong but I don't know what since it's all straight forward.

Cheers,

Steve

**Comment by magenizr** [comment]
Please reopen the issue if you experience the problem in newer Magento versions.
